apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ogtdvsjsa-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:3d134561ebbec0d3dca38562f74262ba79475ee6@sha256:118c93e0a8b8dd513fec499bb1f2cc239000078f1f1f9623b0254f5c7973142b
          name: container-image
